"""Projects as the root of the PostgreSQL schema.

Revision ID: 0001_projects_root
Revises:
Create Date: 2026-10-09

The application moved from SQLite files (`runs.sqlite3`, `seo-agents.sqlite3`)
to one PostgreSQL database. The AI tracker is multi-company: a company is one
project, and `projects` is the main table. A measurement and a brand-check run
carry `project_id NOT NULL REFERENCES projects(id) ON DELETE CASCADE`, so
deleting a project removes everything produced for it and nothing is stored
outside a project.

Old SQLite data is not migrated: this revision creates the current schema on an
empty database.
"""
from __future__ import annotations

from alembic import op

revision = "0001_projects_root"
down_revision = None
branch_labels = None
depends_on = None

# Every object the application owns, in creation order: a referenced table
# exists before the table that points at it.
TABLES: tuple[tuple[str, str], ...] = (
    (
        "projects",
        """
        CREATE TABLE projects (
            id TEXT PRIMARY KEY,
            input_json TEXT NOT NULL,
            revision INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """,
    ),
    (
        "project_measurements",
        """
        CREATE TABLE project_measurements (
            id TEXT PRIMARY KEY,
            project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            snapshot_json TEXT NOT NULL,
            comparison_key TEXT NOT NULL,
            estimate_json TEXT NOT NULL,
            status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            finished_at TEXT
        )
        """,
    ),
    (
        "one_active_project_measurement",
        """
        CREATE UNIQUE INDEX one_active_project_measurement
            ON project_measurements(project_id) WHERE status='running'
        """,
    ),
    (
        "project_measurement_history",
        """
        CREATE INDEX project_measurement_history
            ON project_measurements(project_id, created_at, id)
        """,
    ),
    (
        "project_model_rows",
        """
        CREATE TABLE project_model_rows (
            measurement_id TEXT NOT NULL REFERENCES project_measurements(id) ON DELETE CASCADE,
            query_index INTEGER NOT NULL,
            connection_id TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            evidence_json TEXT,
            brand_mentioned INTEGER NOT NULL DEFAULT 0,
            domain_mentioned INTEGER NOT NULL DEFAULT 0,
            sentiment_status TEXT NOT NULL DEFAULT 'not_applicable',
            sentiment_json TEXT,
            error TEXT,
            sentiment_error TEXT,
            PRIMARY KEY (measurement_id, query_index, connection_id)
        )
        """,
    ),
    (
        "project_search_rows",
        """
        CREATE TABLE project_search_rows (
            measurement_id TEXT NOT NULL REFERENCES project_measurements(id) ON DELETE CASCADE,
            query_index INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            operation_id TEXT,
            documents_json TEXT,
            error TEXT,
            PRIMARY KEY (measurement_id, query_index)
        )
        """,
    ),
    (
        "runs",
        """
        CREATE TABLE runs (
            id TEXT PRIMARY KEY,
            project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            created_at TEXT NOT NULL,
            finished_at TEXT,
            brand TEXT NOT NULL,
            domain TEXT NOT NULL,
            prompts_json TEXT NOT NULL,
            provider_ids_json TEXT NOT NULL,
            regions_json TEXT NOT NULL
        )
        """,
    ),
    (
        "run_project_history",
        "CREATE INDEX run_project_history ON runs(project_id, created_at, id)",
    ),
    (
        "model_rows",
        """
        CREATE TABLE model_rows (
            run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
            provider_id TEXT NOT NULL,
            prompt_index INTEGER NOT NULL,
            provider_name TEXT NOT NULL,
            prompt TEXT NOT NULL,
            status TEXT NOT NULL,
            answer TEXT,
            mentioned INTEGER,
            error TEXT,
            PRIMARY KEY (run_id, provider_id, prompt_index)
        )
        """,
    ),
    (
        "search_rows",
        """
        CREATE TABLE search_rows (
            run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
            search_index INTEGER NOT NULL,
            prompt_index INTEGER NOT NULL,
            region_index INTEGER NOT NULL,
            prompt TEXT NOT NULL,
            region_id INTEGER NOT NULL,
            region_name TEXT NOT NULL,
            engine TEXT NOT NULL DEFAULT 'yandex',
            status TEXT NOT NULL,
            position INTEGER,
            url TEXT,
            error TEXT,
            PRIMARY KEY (run_id, search_index)
        )
        """,
    ),
)

# Tables to drop on downgrade, in reverse dependency order. Indexes disappear
# with their table, so they are not listed again.
TABLES_TO_DROP = (
    "search_rows",
    "model_rows",
    "runs",
    "project_search_rows",
    "project_model_rows",
    "project_measurements",
    "projects",
)


def upgrade() -> None:
    for _name, statement in TABLES:
        op.execute(statement)


def downgrade() -> None:
    for table in TABLES_TO_DROP:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
